name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bookshop
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies
      run: |
        sudo service postgresql start
        python -m pip install --upgrade pip
        pip install -r bookshop/requirements.txt
        pip install pytest-django
    - name: Run migrations
      run: |
        sudo -u postgres createuser -d runner
        sudo -u postgres createdb -O runner bookshop
        pushd bookshop && mkdir log && python manage.py migrate && popd
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port

    - name: Run tests
      run: pushd bookshop && pytest
