on: push
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    container: node:latest

    services:
      # label used to access the service container
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: bookshop
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bookshop/requirements.txt
          pip install pytest-django

      - name: Run migrations
        run: |
          pushd bookshop && mkdir log && python manage.py migrate && popd

      - name: Run tests
        run: pushd bookshop && python manage.py test
