on: push
jobs:
  postgres-job:
    runs-on: ubuntu-latest
    container: node:latest

    services:
      # label used to access the service container
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: bookshop
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Run migrations
        run: |
          sudo -u postgres createuser -d runner
          sudo -u postgres createdb -O runner bookshop

      - name: Query database
        run: psql -h postgres -d postgres -U postgres -c 'SELECT 1;'
        env:
          # postgress password is required; alternatively, you can run:
          # `PGPASSWORD=postgres_password psql ...`
          PGPASSWORD: postgres_password
